// Generates apps/web/src/environments/environment.ts from the repo-root .env.
// WHY: Angular has no runtime env, and we don't want even the (public) anon key
// committed to git. This writes a gitignored environment file at build/serve
// time, sourced from the single .env. Only PUBLIC client values are emitted —
// the service_role key must NEVER appear in the web bundle.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(repoRoot, '.env');

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#') || !trimmed.includes('=')) continue;
    const i = trimmed.indexOf('=');
    out[trimmed.slice(0, i).trim()] = trimmed.slice(i + 1).trim();
  }
  return out;
}

const env = existsSync(envPath) ? parseEnv(readFileSync(envPath, 'utf8')) : {};
const apiPort = env.API_PORT || '3000';

const outPath = resolve(repoRoot, 'apps/web/src/environments/environment.ts');
mkdirSync(dirname(outPath), { recursive: true });

const content = `// GENERATED by scripts/gen-web-env.mjs from the repo-root .env.
// DO NOT edit by hand and DO NOT commit (gitignored). Run \`npm run dev:web\` or
// \`npm run build\` to regenerate. Contains only PUBLIC client config — never the
// service_role key.
export const environment = {
  production: false,
  appName: ${JSON.stringify(env.APP_NAME || 'ExtrovertAI')},
  signupCredits: ${Number(env.SIGNUP_CREDITS ?? 100) || 0},
  supabaseUrl: ${JSON.stringify(env.SUPABASE_URL || '')},
  supabaseAnonKey: ${JSON.stringify(env.SUPABASE_ANON_KEY || '')},
  apiUrl: ${JSON.stringify(`http://localhost:${apiPort}`)},
  devAuthBypass: ${String(env.DEV_AUTH_BYPASS).toLowerCase() === 'true'},
};
`;

writeFileSync(outPath, content);
if (!env.SUPABASE_URL || !env.SUPABASE_ANON_KEY) {
  console.warn(
    '[gen-web-env] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is empty in .env — the web app will not authenticate until these are set.',
  );
}
console.log(`[gen-web-env] wrote ${outPath}`);
